import { FlightDetails } from "../../interface/FlightDetails.interface";

export const dataFlightTickets: FlightDetails[] = [
  {
    price: 12300,
    id: 1,
    from: {
      route: "DXB – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "10:45 – 08:00",
      duration: "14г 15хв",
    },
    to: {
      route: "LHR – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:20 – 00:50",
      duration: "12г 30хв",
    },
  },
  {
    price: 13300,
    id: 2,
    from: {
      route: "DXB – DXB",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "10:45 – 08:00",
      duration: "14г 15хв",
    },
    to: {
      route: "LHR – LHR",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "11:20 – 00:50",
      duration: "12г 30хв",
    },
  },
  {
    price: 42300,
    id: 3,
    from: {
      route: "DXB – DXB",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "10:45 – 08:00",
      duration: "24г 15хв",
    },
    to: {
      route: "LHR – LHR",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "11:20 – 00:50",
      duration: "12г 30хв",
    },
  },
  {
    price: 3300,
    id: 4,
    from: {
      route: "DXB – HKG",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB", "JNB"],
      time: "10:45 – 08:00",
      duration: "24г 15хв",
    },
    to: {
      route: "HKG – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB", "JNB"],
      time: "11:20 – 00:50",
      duration: "26г 30хв",
    },
  },
  {
    price: 15000,
    id: 5,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "10:45 – 8:00",
      duration: "22г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:20 – 0:50",
      duration: "24г 30хв",
    },
  },
  {
    price: 17000,
    id: 6,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["JNB"],
      time: "11:45 – 9:00",
      duration: "23г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["JNB"],
      time: "12:20 – 1:50",
      duration: "23г 30хв",
    },
  },
  {
    price: 19000,
    id: 7,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "12:45 – 10:00",
      duration: "24г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "13:20 – 0:50",
      duration: "22г 30хв",
    },
  },
  {
    price: 21000,
    id: 8,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "10:45 – 8:00",
      duration: "22г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "14:20 – 1:50",
      duration: "24г 30хв",
    },
  },
  {
    price: 23000,
    id: 9,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:45 – 9:00",
      duration: "23г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:20 – 0:50",
      duration: "23г 30хв",
    },
  },
  {
    price: 25000,
    id: 10,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["JNB"],
      time: "12:45 – 10:00",
      duration: "24г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["JNB"],
      time: "12:20 – 1:50",
      duration: "22г 30хв",
    },
  },
  {
    price: 27000,
    id: 11,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "10:45 – 8:00",
      duration: "22г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "13:20 – 0:50",
      duration: "24г 30хв",
    },
  },
  {
    price: 29000,
    id: 12,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "11:45 – 9:00",
      duration: "23г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "14:20 – 1:50",
      duration: "23г 30хв",
    },
  },
  {
    price: 31000,
    id: 13,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "12:45 – 10:00",
      duration: "24г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:20 – 0:50",
      duration: "22г 30хв",
    },
  },
  {
    price: 33000,
    id: 14,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "10:45 – 8:00",
      duration: "22г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: [],
      time: "12:20 – 1:50",
      duration: "24г 30хв",
    },
  },
  {
    price: 35000,
    id: 15,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:45 – 9:00",
      duration: "23г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "13:20 – 0:50",
      duration: "23г 30хв",
    },
  },

  {
    price: 35000,
    id: 16,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:45 – 9:00",
      duration: "23г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "13:20 – 0:50",
      duration: "23г 30хв",
    },
  },
  {
    price: 35000,
    id: 17,
    from: {
      route: "DXB – LHR",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "11:45 – 9:00",
      duration: "23г 15хв",
    },
    to: {
      route: "LHR – DXB",
      status: "В ДОРОЗІ",
      airTransfers: ["HKG", "JNB"],
      time: "13:20 – 0:50",
      duration: "23г 30хв",
    },
  },
];
